# -*- coding: utf-8 -*-
"""Conditionals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blYtAjrBVCemZ4q6UU5Cv93AOjtjxrOg
"""

# 1. ask input to user
number = int( input( "Enter a number: " ) )

# 2. verify the 3 conditions and visualize result
if ( number > 0 ):
    print( "Positive" )
elif ( number < 0 ):
    print( "Negative" )
else:
    print( "Zero" )

"""# Intermediate Exercise:

# Write a Python program that asks the user to enter a temperature in Celsius.
# - If the temperature is below 0, print "Freezing".
# - If the temperature is between 0 and 20 (inclusive), print "Cold".
# - If the temperature is between 21 and 30 (inclusive), print "Warm".
# - If the temperature is above 30, print "Hot".
# Make sure to handle potential errors if the user enters non-numeric input.

# Write your code below this line:
"""

# 1. Ask the use to enter a temperature in Celsius & validate
try:
    temperature = float( input( "Enter the temperatur in Celsius: " ) )

    # 1.1. Verify all conditions and visualize result
    if ( temperature < 0 ):
        print( "Freezing" )
    elif ( temperature >= 0 and temperature <= 20 ):
        print( "Cold" )
    elif ( temperature >= 21 and temperature <= 30 ):
        print( "Warm" )
    else:
        print( "Hot" )

except ValueError:
    print( "That’s not a valid temperature!" )

"""# Advanced Exercise:

# Write a Python program that asks the user to enter a year.
# Determine if the entered year is a leap year.
# A leap year is divisible by 4, but not by 100, unless it is also divisible by 400.
# Print "Leap year" or "Not a leap year" accordingly.
# Make sure to handle potential errors if the user enters non-numeric input.

# Write your code below this line:
"""

# 1. ask the user enter a year and validate input
try:
    year = int( input( "Enter a year: " ) )

    # 1.1 verify if the input is a leap year and print result
    if ( ( year % 4 == 0 ) and not ( year % 100 == 0 ) ) or ( year % 400 == 0 ):
        print( "Leap Year" )
    else:
        print( "Not a Leap Year" )
except ValueError:
    print( "That's not a valid year" )

# 1. ask the user enter a year and validate input
try:
    year = int( input( "Enter a year: " ) )

    # 1.1 verify if the input is a leap year and print result
    if ( ( year % 4 == 0 ) and not ( year % 100 == 0 ) ) or ( year % 400 == 0 ):
        print( "Leap Year" )
    else:
        print( "Not a Leap Year" )
except ValueError:
    print( "That's not a valid year" )